openapi: 3.0.0
info:
  title: Bike Info API
  description: API for managing bike-related data, user feedback, and reviews.
  version: 1.0.0
paths:
  /auth:
    post:
      summary: Authenticate user
      operationId: authenticateUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  token:
                    type: string
        '400':
          description: Missing or invalid email/password
        '401':
          description: Invalid credentials
        '404':
          description: User not found
  /auth/google:
    post:
      summary: Google sign-in authentication
      operationId: signInWithGoogle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                idToken:
                  type: string
      responses:
        '200':
          description: Authentication via Google successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  uid:
                    type: string
                  name:
                    type: string
                  surname:
                    type: string
                  email:
                    type: string
                  role:
                    type: string
                  token:
                    type: string
        '400':
          description: Bad request or Google login failed
        '500':
          description: Internal server error
  /register:
    post:
      summary: Register user
      operationId: registerUser
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad request
  /register/google:
    post:
      summary: Google sign-in registration
      operationId: signInWithGoogle
      responses:
        '201':
          description: User registered successfully with Google
        '400':
          description: Bad request
  /feedbacks/{eid}:
    get:
      summary: Get feedbacks by entity ID
      parameters:
        - name: eid
          in: path
          required: true
          schema:
            type: string
          description: Entity ID
      responses:
        '200':
          description: List of feedbacks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Feedback'
        '404':
          description: Entity not found
    post:
      summary: Post feedback for an entity
      parameters:
        - name: eid
          in: path
          required: true
          schema:
            type: string
          description: Entity ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Feedback'
      responses:
        '201':
          description: Feedback created successfully
        '400':
          description: Missing or invalid data
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /feedbacks/{fid}:
    patch:
      summary: Update feedback
      parameters:
        - name: fid
          in: path
          required: true
          schema:
            type: string
          description: Feedback ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                comment:
                  type: string
      responses:
        '200':
          description: Feedback updated successfully
        '400':
          description: Missing or invalid data
        '401':
          description: Unauthorized
        '404':
          description: Feedback not found
        '500':
          description: Internal server error
  /feedbacks/{fid}/answer:
    patch:
      summary: Admin adds or updates an answer to a feedback
      parameters:
        - name: fid
          in: path
          required: true
          schema:
            type: string
          description: Feedback ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                answer:
                  type: string
      responses:
        '200':
          description: Answer updated successfully
        '400':
          description: Missing or invalid data
        '401':
          description: Unauthorized
        '404':
          description: Feedback not found
        '500':
          description: Internal server error
  /feedbacks/{fid}:
    delete:
      summary: Delete feedback by ID
      parameters:
        - name: fid
          in: path
          required: true
          schema:
            type: string
          description: Feedback ID
      responses:
        '200':
          description: Feedback deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Missing feedback ID
        '401':
          description: Unauthorized
        '403':
          description: Unauthorized to delete this feedback
        '404':
          description: Feedback not found
        '500':
          description: Internal server error
  /reviews/{eid}:
    get:
      summary: Get reviews by entity ID
      parameters:
        - name: eid
          in: path
          required: true
          schema:
            type: string
          description: Entity ID
      responses:
        '200':
          description: List of reviews
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
        '404':
          description: Entity not found
    post:
      summary: Post a review for an entity
      parameters:
        - name: eid
          in: path
          required: true
          schema:
            type: string
          description: Entity ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        '201':
          description: Review created successfully
        '400':
          description: Missing or invalid data
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /reviews/{eid}:
    patch:
      summary: Update a review by entity ID
      parameters:
        - name: eid
          in: path
          required: true
          schema:
            type: string
          description: Entity ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        '200':
          description: Review updated successfully
        '400':
          description: Missing or invalid data
        '401':
          description: Unauthorized
        '404':
          description: Review not found
        '500':
          description: Internal server error
  /reviews/{eid}:
    delete:
      summary: Delete a review by entity ID
      parameters:
        - name: eid
          in: path
          required: true
          schema:
            type: string
          description: Entity ID
      responses:
        '200':
          description: Review deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Missing review ID
        '401':
          description: Unauthorized
        '403':
          description: Unauthorized to delete this review
        '404':
          description: Review not found
        '500':
          description: Internal server error
  /rastrelliere:
    get:
      summary: Get all rastrelliere data
      operationId: getRastrelliere
      responses:
        '200':
          description: List of rastrelliere
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Entity'
        '500':
          description: Internal server error
  /pisteCiclabili:
    get:
      summary: Get all piste ciclabili data
      operationId: getPisteCiclabili
      responses:
        '200':
          description: List of piste ciclabili
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Entity'
        '500':
          description: Internal server error
  /centroInBici:
    get:
      summary: Get all centro in bici data
      operationId: getCentroInBici
      responses:
        '200':
          description: List of centro in bici
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Entity'
        '500':
          description: Internal server error
  /parcheggiProtetti:
    get:
      summary: Get all parcheggi protetti data
      operationId: getParcheggiProtetti
      responses:
        '200':
          description: List of parcheggi protetti
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Entity'
        '500':
          description: Internal server error
components:
  schemas:
    Entity:
      type: object
      properties:
        eid:
          type: string
        name:
          type: string
        description:
          type: string
        geolocation:
          type: array
          items:
            type: number
        type:
          type: string
        rating:
          type: number
    Feedback:
      type: object
      properties:
        fid:
          type: string
        entityId:
          type: string
        uEmail:
          type: string
        comment:
          type: string
        answer:
          type: string
        geolocation:
          type: string
        date:
          type: string
          format: date-time
    Review:
      type: object
      properties:
        entityId:
          type: string
        rating:
          type: number
        uEmail:
          type: string
        uName:
          type: string
        comment:
          type: string
        date:
          type: string
          format: date-time
